"""add conversations and messages tables

Revision ID: 2a30fc3b9f9e
Revises: a0c7078693c6
Create Date: 2026-09-10 15:37:36.350974

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a30fc3b9f9e'
down_revision: str | Sequence[str] | None = 'a0c7078693c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversations',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('tenant_id', sa.String(length=26), nullable=False),
        sa.Column('channel_id', sa.String(length=26), nullable=False),
        sa.Column('customer_external_id', sa.String(length=200), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('assigned_agent_id', sa.String(length=26), nullable=True),
        sa.Column('ai_handling', sa.Boolean(), nullable=False),
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'channel_id', 'customer_external_id', name='uq_conversations_channel_customer'
        ),
    )
    op.create_index(
        'ix_conversations_tenant_status',
        'conversations',
        ['tenant_id', 'status'],
        unique=False,
    )
    op.create_table(
        'messages',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('conversation_id', sa.String(length=26), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content_text', sa.Text(), nullable=False),
        sa.Column(
            'content_blocks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('sender_id', sa.String(length=26), nullable=True),
        sa.Column(
            'tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_messages_conversation_created',
        'messages',
        ['conversation_id', 'created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_tenant_status', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
