"""create llm_usage

Revision ID: 2d62070d80dc
Revises: 56a1e192f78a
Create Date: 2026-09-10 11:24:45.174025

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d62070d80dc'
down_revision: str | Sequence[str] | None = '56a1e192f78a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_request_id'), 'llm_usage', ['request_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_tenant_id'), 'llm_usage', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_tenant_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_request_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
