"""create channel_bindings

Revision ID: a0c7078693c6
Revises: 22bf3e89c240
Create Date: 2026-09-10 11:46:43.376643

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0c7078693c6'
down_revision: str | Sequence[str] | None = '22bf3e89c240'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'channel_bindings',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('channel_id', sa.String(length=26), nullable=False),
        sa.Column('external_conversation_id', sa.String(length=200), nullable=False),
        sa.Column('external_user_id', sa.String(length=200), nullable=False),
        sa.Column('internal_conversation_id', sa.String(length=26), nullable=False),
        sa.Column('tenant_id', sa.String(length=26), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'channel_id', 'external_conversation_id', name='uq_channel_external_conv'
        ),
    )
    op.create_index(
        op.f('ix_channel_bindings_channel_id'),
        'channel_bindings',
        ['channel_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_channel_bindings_tenant_id'),
        'channel_bindings',
        ['tenant_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_bindings_tenant_id'), table_name='channel_bindings')
    op.drop_index(op.f('ix_channel_bindings_channel_id'), table_name='channel_bindings')
    op.drop_table('channel_bindings')
    # ### end Alembic commands ###